$install = "--install-extension"

code $install aaron-bond.better-comments
code $install abusaidm.html-snippets
code $install DavidAnson.vscode-markdownlint
code $install donjayamanne.githistory
code $install dsznajder.es7-react-js-snippets
code $install eamodio.gitlens
code $install esbenp.prettier-vscode
code $install fatihacet.gitlab-workflow
code $install felixfbecker.php-debug
code $install felixfbecker.php-intellisense
code $install felixfbecker.php-pack
code $install formulahendry.auto-close-tag
code $install formulahendry.auto-rename-tag
code $install formulahendry.code-runner
code $install JoeBerria.statusbarerror
code $install mde.select-highlight-minimap
code $install mechatroner.rainbow-csv
code $install ms-python.python
code $install ms-vscode.powershell
code $install ms-vsliveshare.vsliveshare
code $install msjsdiag.debugger-for-chrome
code $install oderwat.indent-rainbow
code $install PeterJausovec.vscode-docker
code $install quicktype.quicktype
code $install ritwickdey.LiveServer
code $install vincaslt.highlight-matching-tag
code $install vscode-icons-team.vscode-icons
code $install vsmobile.vscode-react-native
code $install wayou.vscode-todo-highlight
code $install wix.vscode-import-cost
code $install Zignd.html-css-class-completion
